version: "3.8"

services:
  db:
    container_name: mysql_compose
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul